### ISSUE TITLE
telestion-mavlink-dummy

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#10]
The task is to build a dummy application, which produces MavLink packages and publishes them to a tcp connection.

**Tasks**
- [x] check MavLink documentation
- [ ] define the exact requirements of this application
- [ ] build verticle which starts with the launcher
- [ ] open a TCP connection with the Vert.x api to the telestion application
- [ ] create and send a MavLink-Package
- [ ] listen for MavLink-Packages on TCP and print them
- [ ] write Unit-Tests
