### ISSUE TITLE
telestion-message-dumper

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#13]
This verticle writes messages of a certain kind to a file. This should be used to store MavLink-Packets.

**Tasks**
- [x] define requirements
- [x] listen to the event bus
- [x] store the data in a file
- [ ] write unit tests

**Comment by cb0s** [comment]
Can this be closed?

**Comment by jvpichowski** [comment]
No, it is nearly done and necessary. Just give @oanamateiflorin some time.

**Comment by fussel178** [comment]
@cb0s implemented some parts already in https://github.com/wuespace/telestion-extension-mavlink

**Comment by cb0s** [comment]
@jvpichowski is this still relevant to you or do you think we can close this ?
