### ISSUE TITLE
telestion-mavlink-adapter

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#8]
This task is about to create a MavLink-Adapter which publishes the messages to the eventbus
**Tasks**
- [x] read MavLink docs
- [x] define message and data format for the event bus
- [x] write down requirements
- [x] create a new verticle and run it
- [x] open a TCP port with the Vert.x api
- [x] decode the packages
- [x] publish the data to the eventbus
- [x] listen to the eventbus for packages
- [x] create MavLink-Packages and publish them over TCP
- [ ] write unit tests
